application:
  security:
    secret-key: ${SECRET_KEY}
    expiration: ${EXPIRATION_TIME:1H}
  refresh-token: 
    expiration: ${REFRESH_TIME:7D}


cloud:
  aws:
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET}
